### ISSUE TITLE
Bane has 4 legs.

### ISSUE THREAD

**Issue by micaelbergeron** [JankGaming/herostats-api#2]
Even if they dont touch the ground.
![Look here!](http://img827.imageshack.us/img827/1805/baneviola.png)

**Comment by twisterghost** [comment]
When we originally tallied up the leg count, the rules we went with were:
1. All legs included on the model count, including mounts
2. Legs only count if any one leg touches the ground

The reason for point number 2 is because in the [original video](https://www.youtube.com/watch?v=m3GnjlCVT9Q) for the leg strat joke, Bruno discounts Lina's 2 legs because she's flying.

Seeing as this is probably the most important stat we track, I'm open to debate as to if the legs of totally flying heroes counts or not on a deep, professional level of Dota gameplay.

**Comment by micaelbergeron** [comment]
As we know for certain that Bruno is Icefrog, I dare to imagine he evaluated the best way to count legs strategically wise. 

Closing.
